### ISSUE TITLE
Gapfilling w/ likelihoods raises server error

### ISSUE THREAD

**Issue by gregmedlock** [mmundy42/mackinac#2]
Using mackinac 0.8.0, When attempting the following:

mackinac.gapfill_modelseed_model('97138.3',likelihood=True)

my system returns the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/mackinac-0.8.0-py3.5.egg/mackinac/modelseed.py", line 105, in gapfill_modelseed_model
    _wait_for_job(job_id)
  File "/usr/local/lib/python3.5/site-packages/mackinac-0.8.0-py3.5.egg/mackinac/modelseed.py", line 926, in _wait_for_job
    raise ServerError(task['error'])
KeyError: 'error'

Appears to be on the ModelSEED side, so I tried both of the client urls in the readme to no avail. With likelihood=False, the gapfill is successful.

Thanks!

**Comment by mmundy42** [comment]
There are two things going on here. First, the ModelSEED server no longer returns an 'error' key in the task structure. Mackinac was updated in 0.8.1 to account for the changed server interface (see commit 118444d4e4807c29f57381404ca0f8fabad6d990).

Second, I don't think the ModelSEED server has likelihood support working yet which is probably the cause of the error.
